version: 0.0
os: linux
files:
  - source: binaries
    destination: /webapps/api-de-moedas/
  - source: scripts/apidemoedas.service
    destination: /etc/systemd/system
hooks:
  ApplicationStop:
    - location: scripts/stop_app.sh
      timeout: 120
      runas: root
  ApplicationStart:
    - location: scripts/start_app.sh
      timeout: 120
      runas: root